name: CI

on:
  push:
    branches:
      - main
      - release/**

  pull_request:

env:
  RUSTFLAGS: -Dwarnings

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: clippy, rustfmt, rust-docs
          override: true

      - uses: swatinem/rust-cache@v1
        with:
          key: ${{ github.job }}

      - name: Run Rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Run Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --workspace --all-features --tests -- -D clippy::all

      - name: Rust Doc Comments
        uses: actions-rs/cargo@v1
        env:
          RUSTDOCFLAGS: -Dwarnings
        with:
          command: doc
          args: --workspace --all-features --document-private-items --no-deps

  test:
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]

    name: Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - uses: swatinem/rust-cache@v1
        with:
          key: ${{ github.job }}

      - name: Run Cargo Tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace
