name: CI

on:
  push:
    branches:
      - main
      - release/**

  pull_request:

env:
  RUSTFLAGS: -Dwarnings

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: clippy, rustfmt, rust-docs
          override: true

      - uses: swatinem/rust-cache@v1
        with:
          key: ${{ github.job }}

      - name: Run Rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Run Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --workspace --all-features --tests -- -D clippy::all

      - name: Rust Doc Comments
        uses: actions-rs/cargo@v1
        env:
          RUSTDOCFLAGS: -Dwarnings
        with:
          command: doc
          args: --workspace --all-features --document-private-items --no-deps

  test:
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]

    name: Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - uses: swatinem/rust-cache@v1
        with:
          key: ${{ github.job }}

      - name: Run Cargo Tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace

  test-consumer-image:
    name: Build image for test consumer
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      # `sentry devservices up snuba` picks up the `amd64` version of the image
      # For now, we will publish to a different name until we want to officially
      # support the image on Docker Hub
      # NOTE: This image has only been tested for local development
      CONSUMER_IMAGE: ghcr.io/getsentry/rust-arroyo-test
    steps:
      - uses: actions/checkout@v2
        name: Checkout code

      - name: Get branch name
        id: branch
        # strip `refs/heads/` from $GITHUB_REF and replace `/` with `-` so that
        # it can be used as a docker tag
        run: echo "::set-output name=branch::$(echo ${GITHUB_REF#refs/heads/} | tr / -)"

      - name: Registry login
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
      - name: Pull snuba CI images
        run: |
          docker pull ${CONSUMER_IMAGE}:${{ steps.branch.outputs.branch }} || \
            docker pull ${CONSUMER_IMAGE}:latest || true
      - name: Create Image
        run: |
          docker build \
            -t ${CONSUMER_IMAGE}:latest \
            -t ${CONSUMER_IMAGE}:${{ steps.branch.outputs.branch }} \
            -t ${CONSUMER_IMAGE}:${{ github.sha }} \
            .
      - name: Publish
        # Forks cannot push to the getsentry org
        if: steps.branch.outputs.branch == 'master' || github.event.pull_request.head.repo.full_name == github.repository
        run: |
          # Useful to speed up PRs
          docker push ${CONSUMER_IMAGE}:${{ steps.branch.outputs.branch }}
          if [ "${{ steps.branch.outputs.branch }}" == 'master' ]; then
            # Useful for regression testing on Sentry's checkout
            docker push ${CONSUMER_IMAGE}:${{ github.sha }}
            # The latest tag should only be published on `master`
            docker push ${CONSUMER_IMAGE}:latest
          fi
